export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const REQUEST_TOKEN_SUCCESS = 'REQUEST_TOKEN_SUCCESS';
export const REQUEST_TOKEN_FAILURE = 'REQUEST_TOKEN_FAILURE';
export const SAVE_LOGIN = 'SAVE_LOGIN';
export const UPDATE_SCORE = 'UPDATE_SCORE';
