export const ADD_GRAVATAR = 'ADD_GRAVATAR';

export const ACTIVE_LOGIN = 'ACTIVE_LOGIN';

export const ADD_NEW_QUESTIONS = 'ADD_NEW_QUESTIONS';

export const QUESTION_REQUEST = 'QUESTION_REQUEST';

export const DECREASE_TIME = 'DECREASE_TIME';

export const RESET_TIMER_QUESTION = 'RESET_TIMER_QUESTION';

export const DISABLE_BUTTON = 'DISABLE_BUTTON';

export const SHOW_BUTTON = 'SHOW_BUTTON';

export const RESET_FUNCTIONS = 'RESET_FUNCTIONS';
