export const GET_PLAYER_NAME = 'GET_PLAYER_NAME';

export const GET_PLAYER_EMAIL = 'GET_PLAYER_EMAIL';

export const GET_TOKEN = 'GET_TOKEN';

export const GET_QUESTIONS = 'GET_QUESTIONS';

export const UPDATE_INDEX = 'UPDATE_INDEX';

export const UPDATE_SCORE_ASSERTIONS = 'UPDATE_SCORE_ASSERTIONS';
