export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS';
export const QUESTIONS_FAILURE = 'QUESTIONS_FAILURE';
export const LOGIN_EMAIL = 'LOGIN_EMAIL';
export const LOGIN_NAME = 'LOGIN_NAME';
export const FETCHING_QUESTIONS = 'FETCHING_QUESTIONS';
