export const ADD_USER_INFO = 'ADD_USER_INFO';
export const REQUEST_TRIVIA = 'REQUEST_TRIVIA';
export const GET_TRIVIA = 'GET_TRIVIA';
export const FAILED_TRIVIA_REQUEST = 'FAILED_TRIVIA_REQUEST';
export const ANSWER_CORRECT = 'ANSWER_CORRECT';
export const NEW_SETTINGS = 'NEW_SETTINGS';
